name: Fohn-ui unit test

on:
  pull_request:
  push:

jobs:
  unit-test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with PCOV
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: check path
      run: |
        pwd -P
        pwd -L

    - name: Setup Apache
      uses: ./.github/actions/apache-setup
      with:
        php-version: ${{ matrix.php }}
        site-directory: /home/runner/work/fohn-ui/fohn-ui/
        http-port: 8888

    - name: check port conf
      run: |
        cat /etc/apache2/ports.conf

    - name: check sut conf
      run: |
        cat /etc/apache2/sites-enabled/sut.conf
#    - name: Give apache permission to tests
#      run: |
#        sudo chown -R www-data:www-data /var/www
#        sudo chmod -R og-r /var/www

    - name: "Run php unit"
      run: vendor/bin/phpunit --exclude-group none --no-coverage -v

#    - name: CodeStyle
#      run: composer run-script code-style
#
#    - name: phpstan
#      run: composer run-script phpstan
#
#    - name: Run test suite
#      run: composer run-script unit-test
